### ISSUE TITLE
fix/#9

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch-backend#10]
全てのパターンを自分でテストできないので、時間があればテストを書いてみたいと思います！

Drawingとuserのcreateのためのurlがないです！
DrawingはobjectでPOSTしたくないので、この記事を参考にしていただければと思います！
Drawingはuser_idでPOSTできるようにしてほしいです！
https://sakataharumi.hatenablog.jp/entry/2018/10/20/010806

DrawingのPOSTとGETはurlが被ってしまってAPIViewを継承するクラスベースのViewを作成するくらいしかないので、issueにしてしまいます！

こちらは一旦マージします！

_Originally posted by @mcnLeandro in https://github.com/Recursion-Group-K/sketch-backend/pull/9#issuecomment-1024935627_

**Comment by mcnLeandro** [comment]
> DrawingのPOSTとGETはurlが被ってしまってAPIViewを継承するクラスベースのViewを作成するくらいしかないので、issueにしてしまいます！

こちらですが、generic.ListCreateAPIを使ってください！

```py
class DrawingList(generics.ListCreateAPIView):
  queryset = Drawing.objects.all()
  serializer_class = DrawingSerializer
  permissions_classes = [permissions.IsAuthenticated]
  filter_fields = ('user', 'mode')

class DrawingCreate(generics.CreateAPIView):
  queryset = Drawing.objects.all()
  serializer_class = DrawingSerializer
  permissions_class = [permissions.IsAdminUser]
```
permission_classesはIsAuthenticateOrReadOnlyとcustomePermissionを作成してownerのみの権限でお願いします！
ほぼコピペで行けるはずです。。(DrawingRetrieveUpdateにもお願いします。)
https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#object-level-permissions

------


Userも同じように、generic.ListCreateAPIViewを使ってください！
permissionは少しカスタムしてほしいです！

- SAFE_METHOD(GETとか)はの場合は認証していればOK
- CREATEはrequest.user.is_staff&is_superuser かどうか(IsAdmin)
- PATCH, PUT はrequest.params.id == request.user.id かどうか(isTheUser)
- DELETEは(IsAdmin) || (isTheUser)

自分のロジックとcustompermissionの認識があってればこれで行けるはずです。。。😅


追記：うまくpermissionを作成することができたらもはやViewSetで事足りるかもしれないです。。

**Comment by mcnLeandro** [comment]
userのserializerのfieldにpasswordを入れちゃうと大変なので削除しておきましょう！

**Comment by mcnLeandro** [comment]
current_userのエンドポイントについて忘れてました！
current_userのエンドポイントは

@api_viewデコレータを使って作成しちゃってもいいです！
https://www.django-rest-framework.org/tutorial/2-requests-and-responses/#pulling-it-all-together

上の流れでViewSetでできちゃってる場合は、こちらのリンクの二つ目のエディタの`def highlight(..`みたいにcustome endopointを作成できるはずです！
https://www.django-rest-framework.org/tutorial/6-viewsets-and-routers/#refactoring-to-use-viewsets

ちなみに、自分の理解が合っていれば、中身はこれだけでいいはずです。
```
return Response(request.user) 
```

こちら明日自分もやってみますね

**Comment by tkwonn** [comment]
了解しました！ありがとうございます！

**Comment by tkwonn** [comment]
@mcnLeandro 
Postmanでそれぞれのエンドポイントを確認してみて、意図する挙動を得られなかった部分についてアドバイスお願いしたいです。
（curlを使用した操作などにまだ慣れていないのでPostmanを使用しています。）

1.
HTTP | url | 必要な情報 | 権限 | レスポンス(200)
-- | -- | -- | -- | --
POST | /api/token-auth | 一般ログイン情報 | なし | token

こちらは
```
{
    "detail": "Method \"GET\" not allowed."
}
```
と表示されますが、表示されたページから一般ユーザ情報をいれてPOSTすればtokenを取得できます。
405 Method Not Allowed
これはおそらくURLに一般ユーザ情報を含めていなかっただけだと思うのですが、正しいでしょうか？


2.
HTTP | url | 必要な情報 | 権限 | レスポンス(200)
-- | -- | -- | -- | --
POST | /api/users | 新規ユーザー情報 | 管理者認証 | 新規ユーザー情報
PATCH | /api/users/:id | 更新情報 | Token | ?
POST | /api/drawings | 登録情報 |   | 新規Drawing情報
PATCH | /api/drawings/:id | 更新情報 | Token | ?

500Internal Server ErrorとRuntimeErrorと表示されたHTMLが返されます。
user/permission.pyに原因があるのかとおもうのですが、突き止める事ができませんでした。

3.
GET, DELETEに関しては正常に200 OKが返されますが、POST, PATCHで意図したものが返されていない状態です。

HTTP | url | 必要な情報 | 権限 | レスポンス(200)
-- | -- | -- | -- | --
GET | /api/current_user | Token | なし | 認証しているユーザーの情報
GET | /api-auth/login |   |   |  
GET | /api-auth/logout |  

api/current_userについてはまだできていなくて、login, logoutについてはどのViewを表示すればいいのかわからず暫定的にTokenObtainPairView.as_view()を割り当てている状態です。


長くなり申し訳ありませんが、助けていただけると嬉しいです。よろしくお願いします。

**Comment by tkwonn** [comment]
一度いままでのコードをPUSHしますね。

**Comment by mcnLeandro** [comment]
pushしたらプルリクお願いします！
そこで解答しますね！
