### ISSUE TITLE
fix/is_active

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch-backend#14]
is_activeがfalseの状態でuserが作成されるため一般ユーザーのログインができなくなっているみたいです。
こちらの修正しないといけないです！
![sshot](https://user-images.githubusercontent.com/72016706/151732996-e2da525e-c4d0-4692-bc14-1dcc93086d6c.png)

**Comment by tkwonn** [comment]
承知しました！

**Comment by mcnLeandro** [comment]
ありがとうございます！
一応modelとかいじってみたんですが、なぜか治せなかったです！
治し方わかったら教えてください！🙏

**Comment by tkwonn** [comment]
了解です！返信遅れて申し訳ありませんでした！
自分デフォルトでTrueで作成されるものだと思っていました。

**Comment by mcnLeandro** [comment]
自分もそう思ってました。。
一応default=Trueついているんですが、なぜかっていう感じですね。。。

**Comment by tkwonn** [comment]
管理者画面でもTrueですよね。少し調べてまた連絡します！
![Screen Shot 2022-01-31 at 0
![Screen Shot 2022-01-31 at 0 23 45](https://user-images.githubusercontent.com/66197642/151760691-23d57890-f2a1-4231-b3bd-c2159fdfe9bb.png)
 24 01](https://user-images.githubusercontent.com/66197642/151760682-f8107fd6-5d18-4ac2-b9db-f6a267c521fa.png)

**Comment by tkwonn** [comment]
自分がPostmanでテストしてみた時はTrueですが、curlコマンドで行った際にFalseになるという感じでしょうか？

**Comment by tkwonn** [comment]
user/views.py
```
def perform_create(self, serializer):
    data = serializer.data
    return User.objects.create_user(**data)
```
この場合、おっしゃる通りにis_active=Falseになります

![Screen Shot 2022-01-31 at 2 17 37](https://user-images.githubusercontent.com/66197642/151776053-702e9b88-9397-494e-91ab-cb6cbaf7f474.png)


を以下のように変更しました
```
def perform_create(self, serializer):
    user = User.objects.create_user(**serializer.data)
    user.is_active = True　#強制的にw
    user.save()
    return user
```
すると一応is_active=Trueにはなります
![Screen Shot 2022-01-31 at 2 07 08](https://user-images.githubusercontent.com/66197642/151774766-d3da86a9-5fbf-43e8-a724-e2cb58040b3e.png)

models内ではなく、viewsを変更してやったので、このやり方には少し違和感があるんですが、調べたら多くあるのがis_active=TrueをFalseにしたいという逆の質問ばかりで根本的な修正ができなかったので、これで良いのかっていう感じですが一旦シェアします。

テストしすぎてid番号が、、

**Comment by tkwonn** [comment]
話が変わるんですが、今タイミング悪く引っ越し中でしてテンポが遅れてしまっています。

明後日には集中して取り組めますが、今週の流れを一応確認したいです。

自分の担当の部分でいうと
API通信で意図したデータが返されるようにする
権限を設定
それぞれのエンドポイントを割り振る
テストを書く

このほかにやるべき事は残されていますか？

Issueがでるかもしれないので、そのために余裕をもって終わらせたいですが、ほかにも見落としている部分などがありましたらご指摘お願いします。

**Comment by mcnLeandro** [comment]
ありがとうございます！
一旦、POSTの際にusername, password, is_activeの三つを送ることでうまく行ったのでそれでいきたいと思います！


あと、スーパーユーザーじゃないユーザーのtoken-authについてですが、一般ユーザーはログインができませんでした。
なぜかなと思って調べていたら、パスワードの作り方が違ったから見たいです。
原因はどうやらserializerにパスワードを追加しているかしてないか(id8がしてない、id9がしてる)でした。
調べたところ、passwordはハッシュ化したものを何度もハッシュかしているのでハッシュ後のパスワードを盗まれても、アカウントを乗っ取ることはできないそうです。

それでもpasswordは不必要な情報なので、送りたくないのですが、今回は時間もないですし、serializerにパスワードを追加する方向でいきたいと思います！

![sshot](https://user-images.githubusercontent.com/72016706/151790333-a9250f08-b31e-440b-9540-9012860943e3.png)
-------------

- is_activeはリクエストで一緒に送る
- serializerには一旦passwordを追加で対応

これで一般ユーザーもtokenを取得できるはずです。

**Comment by mcnLeandro** [comment]
@tkwonn 
引っ越しお疲れ様です！
## backend
- JWTのaccece_tokenが切れたときにrefresh_tokenを使ってaccecss_tokenを再取得する部分
- imageのアップロードについて
https://medium.com/@kaizumaki/django-drf-vue-vuetify-824083717f15

## frontend
jinさんにフロント側のAPI通信とログインを任せていたのですが、僕とkwonさんと3人でやっちゃおうかなと考えてました！

## 
他は細かいバグがあれば修正するのくらいですね！
明日はバックエンドの部分僕がやっておくので無理しないでも問題ないですよ👍

**Comment by tkwonn** [comment]
@mcnLeandro 

なるほど！確かにPostmanでこの前教えていただいたform-dataにusername, passwordと一緒にis_active = Trueをつけたらいけましたね。

それでは、
is_activeの部分は変更前に戻す。
今回は、serializerに一旦passwordを追加。
してからプッシュしておきます。

残りのbackend, frontendの部分、了解しました！

ありがとうございます！後少しですね。

**Comment by mcnLeandro** [comment]
あ、ごめんなさい！
今ちょうどpushしちゃいました！
それをそのままマージするので、ローカルでプルしておいてください🙏

**Comment by tkwonn** [comment]
了解です！！ありがとうございます！
