### ISSUE TITLE
endpoint: current_user

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-K/sketch-backend#15]
#2 

HTTP | url | 必要な情報 | 権限 | レスポンス(200)
-- | -- | -- | -- | --
GET | /api/current_user | Token | なし | 認証しているユーザーの情報

このURlエンドポイントが返す情報というのは、認証しているユーザ全員ですか？（is_active=Trueのユーザ全員？）
それとも、ログインしているユーザが自分のユーザ情報を取得する時に使用するものでしょうか？

前者ならやり方としては、ListAPIViewにフィルターをかけて取得するのを考えていて、
```
class UserDetail(generics.ListAPIView):
  queryset = User.objects.filter(user=request.user)
```
後者ならRetrieveAPIViewでrequest.params.id == request.user.idが一致したらみたいな感じで考えていましたが、どうでしょうか？

質問多くて恐れ入りますが、宜しくお願いします。

**Comment by mcnLeandro** [comment]
後者です！
そうですね。。本来はそうしたいんですが、

今回Front側で保存しているのはTokenだけなので、users/:id の:idの部分がわからないんですよね。
解決策は
idをfront側でCookieにtokenと一緒に保存することですが、こうしますか？

**Comment by tkwonn** [comment]
そうですね。
ちなみにヘッダーにログイン時に取得したトークンを追加してGETメソッドを投げる方法というのはできないのでしょうか？

**Comment by mcnLeandro** [comment]
できますよ！
最初に言っていたのがそれです！
request.userをreturnするだけでOKになるはずです！

**Comment by tkwonn** [comment]
なるほど！理解しました。
本来のやり方でやります！ありがとうございます！

**Comment by tkwonn** [comment]
レアンドロさんがCORSの設定の部分でブランチを切ってbackend/settings.pyを修正してくださったと思うのですが、そちらもfeat/api/drawingに反映させてプッシュした方がよろしいですか？

**Comment by mcnLeandro** [comment]
そうですね！一旦developをプルして進めていただくか
developからブランチ切っても良いです！
