### ISSUE TITLE
feat/image/upload

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch-backend#18]
cloudinaly
https://qiita.com/koki276/items/4f78ca421bea059d7b7a
imageのアップロードについて vueから
https://medium.com/@kaizumaki/django-drf-vue-vuetify-824083717f15

**Comment by tkwonn** [comment]
2つ目の記事は画像のアップロードですが、この機能は今回使用しますか？

cloudinalyはインストールとsettings.pyへの書き込みをする部分だけ今のところ追加すればよろしいでしょうか？

**Comment by mcnLeandro** [comment]
そうですね！

興味があればcloudinalyのアカウントを作っていただいても問題ないです！
一応僕も作るつもりです！

でもAPI_KEYとかはgitにあげない方がいいのでlocal_settings.pyを作ってそこに記述したのをimportするといいです！

**Comment by tkwonn** [comment]
了解です！ありがとうございます！

**Comment by mcnLeandro** [comment]
## 進捗
全て記述してstagingで検証するだけ。
だけどherokuが落ちてるみたいでpushできず

ひとまず待機
今のうちにフロントの様子見に行ってきます

**Comment by mcnLeandro** [comment]
うまくいった
