### ISSUE TITLE
confirm: issueの分割についての確認

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-K/sketch-backend#5]
@mcnLeandro 
イシューの作成時にAssigneesの部分にassign-yourselfや歯車マークがなぜか表示されなかったのでメンションにて失礼します。

filetreeから引用
backend/
	├-user/
	├-drawing/
	├-project/
	|	├-settings.py
	|	├-local_settings.py
	|	:
	└-.gitignore

## mainブランチ

環境構築を行う
- django, rest_framework, venv
- project作成（名前はbackend)

## feat/api/user & feat/api/drawing

https://github.com/jakemcdermott/vue-django-rest-auth
こちらの記事でいうとapiディレクトリをuser, drawingで分けるという認識であってますか？（つまり、startapp user, startapp drawing?)

- models.py, urls.py, views.py, serializers.pyを先に進めたいと思っています。

## client

https://nmomos.com/tips/2019/07/17/django-vuejs-1/　
こちらの記事のように確認用に簡単なクライアントのログイン画面みたいのは作成した方がいいでしょうか

特にJWT認証の部分が曖昧で、
https://nmomos.com/tips/2019/07/24/django-jwt-authentication/
こちらの記事通り進めていて
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' というエラーにより最後まで進められませんでした。
（記事自体は最後まで確認済みです）

自分の理解が不足していて、認識がズレているかもしれませんが宜しくお願いします。
細かい部分の処理などは端折っていますが、issue作成時はもっと細かく確認する予定です。

**Comment by mcnLeandro** [comment]
@tkwonn 
コラボレーターに招待するのを忘れていたので招待しておきました！
> こちらの記事でいうとapiディレクトリをuser, drawingで分けるという認識であってますか？（つまり、startapp user, startapp drawing?)

そういうことになります！
カスタムユーザーを作成する際にUserが肥大化するのでモデル単位で分けます！

> ImportError: cannot import name 'smart_text' from 'django.utils.encoding' というエラーにより最後まで進められませんでした。

こちらのエラーは実際に見てみないとわかりませんがファイルの一番上に実は全然関係ないパッケージインポートしていたとかが原因だったり、名前は同じでもimport先が違ったりではないでしょうか？

jwt認証は僕もまだ試していなくて、rest_frameworkが提供しているtoken auth を実装しただけなので一回こっちを実装するといいです。

https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

自分はdoc通りすすめてもできない部分があったので途中からは別の記事とか参考にするのもありです。
jwtは別でdocumetがあるのでこれ通りに進めてもいいかもしれないです！

https://jpadilla.github.io/django-rest-framework-jwt/

**Comment by mcnLeandro** [comment]
> こちらの記事のように確認用に簡単なクライアントのログイン画面みたいのは作成した方がいいでしょうか

ログイン画面は作成しなくても大丈夫ですが、時間があればやってみてもいいです！
一番大事なのは認証してtokenが取得できるかどうかが大事ですね！

> models.py, urls.py, views.py, serializers.pyを先に進めたいと思っています。

ありがとうございます！
Viewに関して
個人的にはrest_frameworkのgeneric ClassBaseed Viewを使うといいかなと思います！
ClasseBasedもですがViewSetだとはまとめて作ってしまうので一個一個の権限の設定とかができないので。。。

https://www.django-rest-framework.org/api-guide/generic-views/

**Comment by tkwonn** [comment]
@mcnLeandro 
了解です！ ありがとうございます！

では
1. 環境構築
2. feat/api/user作成
3. feat/api/drawing作成

tokenを取得できるようにする

という流れで進めていきます。

2, 3に関しては通常どおりissueを作成し、途中経過を報告しながら進めていきますね。

ViewSetではなくGenericを使用する点とjwt認証の件、承知いたしました！

**Comment by tkwonn** [comment]
管理者用ページのユーザネームとパスワードは何で統一すればよいでしょうか？

**Comment by mcnLeandro** [comment]
管理者用の名前をパスワードは開発環境であればなんでも問題ないです！
本番ではpassword generatorを使って管理者パスワードを作ろうかなと考えてます！
https://www.graviness.com/app/pwg/

**Comment by tkwonn** [comment]
了解です！

先日カスタムUserを作成してそれを利用するとおっしゃっていたのを思い出したのですが、それは
https://docs.djangoproject.com/en/4.0/topics/auth/customizing/
こちらのリンクで書かれている事と同じような感じですか？

もしそうであれば、cketch-backend-testで行っているようなやり方でimportする事になると思うのですが、userディレクトリにはカスタム内容を書くという事になるという事ですか？

**Comment by mcnLeandro** [comment]
そうですね！
この中のAbstructBaseUserを継承する部分がそれにあたります！
https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#specifying-a-custom-user-model

これに関してはたくさん記事があるので参考にできるはずです（自分はまだ作った事がないのですが、お願いします。自分も時間ができたらDjangoのかけている知識を保管して行きます）

https://qiita.com/gaku3601/items/9ca3695bb8b18bed5d5e
https://qiita.com/gaku3601/items/19f734fedd5fe19e5c77

**Comment by tkwonn** [comment]
了解です！ありがとうございます！
